name: epitopepredict
version: 'latest'
version-script: git describe --abbrev=1 --tags
summary: python package for MHC binding prediction
description: |
 epitopepredict is a python package and command line interface that provides a standardized
 programmatic interface for executing several MHC binding prediction methods. The results from
 each method can then be processed and visualized in a consistent manner.

grade: stable
confinement: strict
icon: gui/icon.png

apps:
  epitopepredict:
    command: bin/epitopepredict
    plugs: [home,network-bind]
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/ncbi-blast+  
parts:
  epitopepredict:
    plugin: python
    python-version: python3
    source: ../
    python-packages:
      [mhcflurry,gtfparse==1.2,pyensembl==1.7.3,varcode==0.8.0]
    stage-packages:
      [gawk,ncbi-blast+]
