name: epitopepredict
version: 'latest'
version-script: git describe --abbrev=1 --tags
summary: python package for MHC binding prediction
description: |
 epitopepredict is a python package and command line interface that provides a standardized
 programmatic interface for executing several MHC binding prediction methods. The results from
 each method can then be processed and visualized in a consistent manner.

grade: stable
confinement: strict
icon: ../img/logo.png

apps:
  epitopepredict:
    command: bin/epitopepredict
    plugs: [home,network-bind] 
parts:
  epitopepredict:
    plugin: python
    python-version: python2
    source: ../
    python-packages:
      [matplotlib,sklearn]
    stage-packages:
      [python-tk,tcsh,gawk,ncbi-blast+]
  #netmhciipan:
  #  plugin: autotools
  #  source:
