name: epitopepredict
version: 'latest'
version-script: git describe --abbrev=1 --tags
summary: python package for MHC binding prediction
description: |
 epitopepredict is a python package and command line interface that provides a standardized
 programmatic interface for executing several MHC binding prediction methods. The results from
 each method can then be processed and visualized in a consistent manner.

grade: stable
confinement: strict
icon: gui/icon.png

apps:
  epitopepredict:
    command: bin/epitopepredict
    plugs: [home,network-bind]
    environment:
      PYENSEMBL_CACHE_DIR: $SNAP_USER_COMMON
parts:
  epitopepredict:
    plugin: python
    python-version: python2
    source: ../
    python-packages:
      [matplotlib,mhcflurry,sklearn,gtfparse==0.0.6,pyensembl==1.1,varcode==0.5.15,mhcnuggets]
    stage-packages:
      [tcsh,gawk,ncbi-blast+,bowtie2]
  #netmhciipan:
  #  plugin: autotools
  #  source:
